name: Delete review package on closed PR

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PACKAGE_NAME: ${{ github.event.repository.name}}-service

jobs:
  delete_image:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to get access to branch name and other metadata
    - name: Checkout repository
      uses: actions/checkout@v3

    # Get repository and branch name for the Docker image tag
    - name: Set image name and tag
      id: set_image_name
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}:${{ github.head_ref }}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    # Delete the Docker image from GHCR
    - name: Delete Docker image from GHCR
      run: |
        IMAGE_NAME=${{ env.IMAGE_NAME }}
        echo "Deleting image $IMAGE_NAME from GHCR..."
        # Extract image name and version (without repository)
        IMAGE_PATH="${IMAGE_NAME##*/}"
        IMAGE_VERSION="${IMAGE_PATH##*:}"
        GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        OWNER="${{ github.repository_owner }}"

        # Get all versions of the image and find the version ID
        IMAGE_VERSION_ID=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/users/$OWNER/packages/container/$PACKAGE_NAME/versions" | \
          jq -r '.[] | select(.metadata.container.tags[] == "'"$IMAGE_VERSION"'") | .id'
        )

        if [ -z "$IMAGE_VERSION_ID" ]; then
          echo "Image version not found."
          exit 1
        fi

        # GitHub API URL for deleting the image version
        DELETE_URL="https://api.github.com/users/$OWNER/packages/container/keyglide-service/versions/${IMAGE_VERSION_ID}"

        # Delete the image version
        curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$DELETE_URL"




